SELECT COUNT(*)
FROM Production.Product
-- ACIMA SABEMOS A QUANT DE PROD NA TAB
SELECT count(size)
FROM Production.Product
--ACIMA SABEMOS QUANTOS TAMANHOS DE PROD TEMOS NA TAB
SELECT count(DISTINCT size)
FROM Production.Product
--TAMANHOS DISTINTOS
